### ISSUE TITLE
Switches have different focus ring color and offset

### ISSUE THREAD

**Issue by matthewpaulthomas** [vanilla-framework/vanilla-framework#1759] opened 2018-04-23 11:32 UTC
The focus appearance for a Vanilla switch is:
```css
  outline: 1px solid #007aa6;
  outline-offset: 3px;
```
![vanilla-focus-switch](https://user-images.githubusercontent.com/19801137/39124139-3c034292-46f2-11e8-8d52-53c032bc817f.png)

The focus appearance for, apparently, all other Vanilla controls is
```css
  outline: 1px solid #19b6ee;
  outline-offset: 2px;
```
![vanilla-focus-button](https://user-images.githubusercontent.com/19801137/39124142-40161a8a-46f2-11e8-90f8-4cc3bc73aad2.png)

At least the color should be consistent. The offset probably should be consistent too.

**Comment by spencerbygraves** [comment] 2018-04-23 13:56
#19b6ee isn't a Vanilla colour (it was the old link colour) and #007aa6 is now the link colour.  So I think we should be using color-information (#335280) was intended for focus and selection.

**Comment by spencerbygraves** [comment] 2018-04-23 15:10
@kwm14 ok, thanks. I thought Jamie had used the darker one, my mistake.

**Comment by kwm14** [comment] 2018-05-17 11:12
This will be fixed as part of this [PR](https://github.com/vanilla-framework/vanilla-framework/pull/1820) 👍

**Closed** 2018-05-21 08:32 UTC
Labels: Priority: Low
