### ISSUE TITLE
Headings labelled incorrectly on /base/typography

### ISSUE THREAD

**Issue by Greggless** [vanilla-framework/vanilla-framework#1833] opened 2018-05-24 11:02 UTC
## Process

https://docs.vanillaframework.io/en/base/typography

## Expected result

Headings to range from 1-->6, decreasing in height

## Current result

Headings range from 6-->1, decreasing in height

**Comment by Caleb-Ellis** [comment] 2018-05-25 08:54
Closing as it's a duplicate of #1832

**Closed by Caleb-Ellis** 2018-05-25 08:54 UTC
