### ISSUE TITLE
Confusing spacing of single element columns

### ISSUE THREAD

**Issue by bartaz** [vanilla-framework/vanilla-framework#1340] opened 2017-09-14 09:36 UTC
While working with Vanilla grid I found it a bit confusing that additional margin is added sometimes to single element columns.

Consider such example (:
 
```html
<div class="p-strip is-bordered">
  <div class="row">
     <div class="col-12">
         <h1>
         test
         </h1>
     </div>
  </div>
</div>
```

See also at https://jsfiddle.net/oast2kk1/

Even though equal spacing is defined on top and bottom by Strip pattern, there is additional bottom margin added:

<img width="658" alt="screen shot 2017-09-14 at 11 26 18" src="https://user-images.githubusercontent.com/83575/30422391-0ba35f20-9940-11e7-8743-9b33a0fa0491.png">

It's caused by very specific `.row:first-of-type [class^="col-"]:only-child > *:only-child` rule.
https://github.com/vanilla-framework/vanilla-framework/blob/develop/scss/_base_vertical-spacing.scss#L81-L83

I suppose this additional spacing was added to solve some common issue, but it happens to add spacing also when it's not expected. Especially that it happens only for the first row (`first-of-type`) to the only child of single column.

Maybe issue here is that if conflicts with the `p-strip` spacing, or maybe it would be worth to document such spacing rules with examples, so they could be better understood by devs new to Vanilla grid.

I worked around the issue by adding `u-no-margin--bottom` utility to the single child element, but maybe there could be a better solution?

**Comment by anthonydillon** [comment] 2017-09-14 22:53
You are absolutely correct here. There are some major issues with the current vertical spacing of Vanilla framework. There is a critical issue to resolve: https://github.com/vanilla-framework/vanilla-framework/issues/1338.

The issue is. There are a lot of combinations to patterns which require a lot of logical CSS (which of course, it is not good at). The code the mentioned solves the issue of having your code with a strip underneath. This creates spacing between them.

I think your fix for now is a good one as it will continue to work once this has been resolved.

**Comment by anthonydillon** [comment] 2017-09-14 22:54
Going to close this one as a duplicate of https://github.com/vanilla-framework/vanilla-framework/issues/1338.

I will be sure to reference your example when exploring a solution.

**Closed by anthonydillon** 2017-09-14 22:54 UTC
