### ISSUE TITLE
The external icon is erroneously cropped on webkit

### ISSUE THREAD

**Issue by deadlight** [vanilla-framework/vanilla-framework#1387] opened 2017-10-19 12:32 UTC
On webkit browsers, external link icons (.p-link--external) don't display correctly - the icon is cropped badly.

Locally, on ubuntu.com, I'm fixing this issue with the following:

```
.p-link--external::after {
  -webkit-mask-size: cover;
}
```

**Comment by kwm14** [comment] 2017-10-19 12:57
Thanks @deadlight 

@grahambancroft also experienced this bug when updating maas.io. We have marked it as a high priority push and moved it to Maintenance during this iteration.

Issue created to fix: https://github.com/vanilla-framework/vanilla-framework/issues/1380

**Comment by barrymcgee** [comment] 2017-10-24 08:18
Closing as duplicate of #1380

**Closed by barrymcgee** 2017-10-24 08:18 UTC
