### ISSUE TITLE
Missing bottom padding on divider list p-icon header

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1717] opened 2018-04-13 16:00 UTC
## v1.7.0-beta-1 review on ubuntu.com

Currently the middle item in the divider list is missing padding `16px` below p-icon header, not sure why this is happening but it's fine on the other items to the left and right of it.
- Issue can be found here: http://www.ubuntu.com-pr-2952.run.demo.haus/openstack and http://www.ubuntu.com-pr-2952.run.demo.haus/cloud/foundation-cloud

## Current result
![screen shot 2018-04-13 at 16 53 58](https://user-images.githubusercontent.com/17748020/38745185-c1a657d6-3f3b-11e8-9f07-e93077ba7cb7.png)

**Comment by lyubomir-popov** [comment] 2018-04-19 13:40
This looks like a duplicate of 1731. I've made a pr for it, I suggest we close this @kwm14

**Comment by Caleb-Ellis** [comment] 2018-04-24 14:52
Seems to already be fixed on https://github.com/canonical-websites/www.ubuntu.com/pull/3035

**Closed by Caleb-Ellis** 2018-04-24 14:52 UTC
Labels: v1.7.0-beta-1
