### ISSUE TITLE
Why margin-top: -1.1rem on p + p:not(.p-muted-heading)?

### ISSUE THREAD

**Issue by nottrobin** [vanilla-framework/vanilla-framework#2019] opened 2018-10-08 16:58 UTC
Basically paragraphs next to other paragraphs have `margin-top: -1.1rem`. This makes `<p>` elements interact very weirdly next to other empty `<p>` elements.

Why do they have this? Could it be removed? Otherwise, could we add:

``` scss
p:empty + p:not(.p-muted-heading), p + p:not(.p-muted-heading):empty, p:empty + p:not(.p-muted-heading):empty {
  margin-top: 0;
}
```

(Like I did here https://github.com/canonical-websites/discourse-docs.snapcraft.io/pull/42/files#diff-9f40d64fd95564c5ba27a3ef536cb50fR87 )

**Comment by kwm14** [comment] 2018-10-15 12:39
## Agreed in WG
- @deadlight try using last of type on paragraphs to see if this solution works

**Comment by deadlight** [comment] 2018-11-16 16:34
This is caused by some - quite complex - workarounds for the spacing between paragraphs not being the same size as a line of text.

It has been decided paragraphs should have their spacing simplified, removing the need for hacks and workarounds.

Your issue will be fixed - and your local workaround can be removed - when #2026 is closed and released.

**Comment by kwm14** [comment] 2019-02-11 11:21
Fixed inside @lyubomir-popov typographic refractor for 2.0 https://github.com/vanilla-framework/vanilla-framework/issues/2128 💯

**Closed by kwm14** 2019-02-11 11:21 UTC
Labels: WG: Validated
