### ISSUE TITLE
Delete icon is not centred

### ISSUE THREAD

**Issue by bartaz** [vanilla-framework/vanilla-framework#2085] opened 2018-12-21 16:07 UTC
`p-icon--delete` seems not to be fully centered within its box, making it look a bit misaligned compared to other icons:

<img width="456" alt="screen shot 2018-12-21 at 17 06 11" src="https://user-images.githubusercontent.com/83575/50351577-e9ccbc00-0542-11e9-816e-401a9a11741e.png">
<img width="468" alt="screen shot 2018-12-21 at 17 06 23" src="https://user-images.githubusercontent.com/83575/50351581-edf8d980-0542-11e9-96b4-a6512e0aaae1.png">

**Comment by leesheppard** [comment] 2018-12-22 08:05
Can confirm that the issue is in the SVG code. The icon is 13px wide in a 16px box.

**Comment by deadlight** [comment] 2019-01-09 08:45
Thanks for reporting this. We can re-export it from the original file with the correct-sized canvas. 

I'll let you know when it's landed in master - you could backport it locally until the next Vanilla release.

**Closed** 2019-01-10 16:01 UTC
