### ISSUE TITLE
Jump in navigation pattern on page load

### ISSUE THREAD

**Issue by barrymcgee** [vanilla-framework/vanilla-framework#1275] opened 2017-08-17 08:36 UTC
When you load a page using the navigation pattern (e.g. https://vanillaframework.io/), the last item will 'jump' when the page loads. 

![screen recording 2017-08-17 at 09 34 am](https://user-images.githubusercontent.com/505570/29403198-84398d32-832f-11e7-87da-52a94c87d461.gif)

**Comment by barrymcgee** [comment] 2017-09-14 11:36
I've dug into this and figured out what is causing this. Because we can't specify a width on navigation items due to the variable nature of navigation labels, these items are `display: inline-block` - this means that on first page load, there's is a calculation that needs to be made on how wide the list item needs to be which will result in the nav item page jump. Once this happens once, it is cached and does not happen again unless the cache is cleared. The fix which resolves this is to add a width onto each list element which is not something we can do at a framework level therefore it's something we'll have to live with.

**Comment by anthonydillon** [comment] 2017-09-19 08:17
I don't believe this is the true reason. The navigation items are floated and all browser layout calculations are complete before the page is displayed. 

I think this is caused by the font displaying as the default until the font itself loads. Then the items become the font-weight 300. Which is slightly thinner than the regular.

**Comment by barrymcgee** [comment] 2017-09-21 10:42
Having throttled my connection, I agree with your analysis. The main workaround for this is to hide the content on the page until all assets have loaded then show it - feels very wrong to me.

The only other action we might be able to take is to try and improve the latency from the assets server?

**Comment by anthonydillon** [comment] 2017-09-21 14:17
In fact, the jump is there on all of our sites. I think we can consider this closed as its a font loading issue.

**Closed by anthonydillon** 2017-09-21 14:17 UTC
Labels: Type: Bug
