### ISSUE TITLE
Update vertical padding value on List with dividers component

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1581] opened 2018-02-08 10:31 UTC
## Process

1. Navigate to https://docs.vanillaframework.io/en/patterns/lists#list-with-dividers
2. Design spec https://github.com/ubuntudesign/vanilla-design/blob/master/Lists/lists.md

## Expected result
- vertical-padding: `8px`

## Current result
- vertical-padding: `10px`

## Screenshot
![screen shot 2018-02-08 at 10 05 26](https://user-images.githubusercontent.com/17748020/35968121-da65bafe-0cba-11e8-96ba-a49479aa6db7.png)

**Comment by Caleb-Ellis** [comment] 2018-03-07 15:30
duplicate of #1582

**Closed by Caleb-Ellis** 2018-03-07 15:30 UTC
Labels: Priority: Low, Type: Enhancement
