### ISSUE TITLE
Combine dashboard icons pattern 

### ISSUE THREAD

**Issue by anthonydillon** [vanilla-framework/vanilla-framework#1248] opened 2017-08-05 20:34 UTC

**Comment by matthewpaulthomas** [comment] 2017-08-17 09:03
(Based on the summary, and the population of other “Combine…” issues, this looks to be a duplicate of #1230. I can’t be sure because neither has a description.)

**Comment by barrymcgee** [comment] 2017-08-17 09:06
@matthewpaulthomas Looks like it, yes. Thanks.

**Closed by barrymcgee** 2017-08-17 09:06 UTC
