### ISSUE TITLE
Matrix is misaligned

### ISSUE THREAD

**Issue by spencerbygraves** [vanilla-framework/vanilla-framework#1689] opened 2018-04-05 13:45 UTC
## ubuntu.com v1.7.0-alpha-1
Reviewing the beta test branch, the matrix is misaligned with too much space on the left.

I think it's .p-matrix__item::before, which should be removed if there's no image.

### Current result
![image](https://user-images.githubusercontent.com/9105999/38369504-c2823970-38df-11e8-8773-1863aa18eba5.png)

**Comment by kwm14** [comment] 2018-04-06 10:40
Duplicate of https://github.com/vanilla-framework/vanilla-framework/issues/1670

**Closed by kwm14** 2018-04-06 10:40 UTC
Labels: Type: Bug, v1.7.0-alpha-1
